config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :update]
  resources :cards, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: PASSWORD_REGEX }, allow_blank: true
  validates :password, presence: true, on: :create
  with_options presence: true do
    validates :nickname
    validates :birthday
    validates :last_name
    validates :first_name
    validates :phonetic_last
    validates :phonetic_first
  end
  with_options allow_blank: true do
    with_options format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ } do
      validates :last_name
      validates :first_name
    end
    with_options format: { with: /\A[ァ-ヶー－]+\z/ } do
      validates :phonetic_last
      validates :phonetic_first
    end
  end

  has_many :items
  has_many :orders
  has_many :comments
  has_one :card, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] # 環境変数を読み込む
    card = Card.find_by(user_id: current_user.id) # ユーザーのid情報を元に、カード情報を取得
    if current_user.card.present?
      customer = Payjp::Customer.retrieve(card.customer_token) # 先程のカード情報を元に、顧客情報を取得
      @card = customer.cards.first
    end
  end

  def update
    if current_user.update(user_params) # 更新出来たかを条件分岐する
      redirect_to root_path # 更新できたらrootパスへ
    else
      redirect_to action: "show" # 失敗すれば再度マイページへ
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email) # 編集出来る情報を制限
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="AccountPage">
  <div class="AccountPage__title">
    <h1>マイページ</h1>
  </div><br>
  <% if current_user.card.present? %>
    <div class="Card__title">
    <h2>カード情報</h2>
  </div>
  <div class="Card_info">
    【カード番号】
    <br>
    <%= "**** **** **** " + @card[:last4] %>
    <%# カード番号の下4桁を取得 %>

    <br>
    【有効期限】
    <br>
    <%= @card[:exp_month] %>
    <%# 有効期限の「月」を取得 %>
    /
    <%= @card[:exp_year] %>
    <%# 有効期限の「年」を取得 %>
  </div>
  <div class="Account__info">
    <h2>ユーザー情報</h2>
  </div>
  <% end %>
  <div class="AccountPage__form">
    <%= form_for(current_user) do |f| %>
      <div class="FormField">
        <div class="FormField__name">
          <%= f.label :name %>
        </div>
        <div class="FormField__name">
          <%= f.text_field :nickname, autofocus: true %>
        </div>
      </div>
      <div class="FormField">
        <div class="FormField__email">
          <%= f.label :email %>
        </div>
        <div class="FormField__email">
          <%= f.email_field :email %>
        </div>
        <br>
      </div>
      <%= f.submit "更新する" %>
    <% end %>
    <br>
    <%= link_to "クレジットカード情報を登録する", new_card_path %>
    <br>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
    <br>
    <%= link_to "商品一覧へ戻る", root_path%>
  </div>
</div>